apiVersion: onosjob.com/v1alpha1
kind: ONOSJob
metadata:
  name: example-onosjob
spec:
  controller-ip: 10.0.2.15
  controller-port: 30120
  hosts:
  - mac: 46:E4:3C:C4:17:C8
    vlan: "None"
    ipAddresses:
    - 10.0.0.8
    locations:
    - elementId: of:0000000000000001
      port: 8
  flows-device:
  - deviceId: of:0000000000000001
    priority: 40000
    isPermanent: true
    timeout: 0
    instructions:
    - type: "output"
      port: "controller"
    criteria:
    - type: "eth_type"
      ethType: 0x88cc
