apiVersion: onosjob.com/v1alpha1
kind: ONOSJob
metadata:
  name: example-onosjob
spec:
  controller-ip: "10.244.0.47"
  controller-port: "8181"
  hosts:
  - mac: "46:E4:3C:C4:17:C8"
    vlan: "None"
    ipAddresses:
    - "10.0.0.8"
    locations:
    - elementId: "of:0000000000000001"
      port: "8"
  flowsDevice:
  - deviceId: "of:0000000000000001"
    appId: "123"
    priority: 47000
    isPermanent: true
    timeout: 0
    instructions:
    - type: "OUTPUT"
      port: "CONTROLLER"
    criteria:
    - type: "ETH_TYPE"
      ethType: "0x88cc"
